version: 2.1

################################
# Aliases

aliases:
  - &dir ~/repo
  - &attach_workspace
    attach_workspace:
      at: *dir
  - &cache-key dependency-cache-lts-{{ checksum "package.json" }}
  - &cache-key-fallback dependency-cache-

################################
# Executors

executors:
  default:
    working_directory: *dir
    docker:
      - image: cimg/node:lts


################################
# Jobs

jobs:
  checkout_code:
    executor: default
    steps:
      - checkout
      - persist_to_workspace:
          root: *dir
          paths:
            - .

  test:
    executor: default
    steps:
      - *attach_workspace
      - restore_cache:
          keys:
            - *cache-key
            - *cache-key-fallback
      - run:
          name: install dependencies with npm
          command: npm install
      - run:
          name: rebuild dependencies with npm -- in case node version changed
          command: npm rebuild
      - save_cache:
          key: *cache-key
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Compile the files using Babel
          command: npm run compile
      - persist_to_workspace:
          root: *dir
          paths:
            - node_modules
            - dist

  release:
    executor: default
    steps:
      - *attach_workspace
      - run:
          name: Copy core files to the /dist folder
          command: npm run copypackage
      - run: npm run semantic-release

  publish-docs:
    executor: default
    steps:
      - *attach_workspace
      - add_ssh_keys:
          fingerprints:
             - "12:bf:d1:9d:22:ec:c3:4f:72:44:50:77:61:70:a0:1e"
      - checkout
      - run:
          name: Set names
          command: git config --global user.email "bot@5app.com" && git config --global user.name "UI release bot"
      - run:
          name: Build & deploy docs to gh-pages
          command: npm run deploy-docs

workflows:
  build:
    jobs:
      - checkout_code
      - test:
          requires:
            - checkout_code
      - release:
          context: org-global
          requires:
            - test
      - publish-docs:
          context: org-global
          requires:
            - test
          filters:
            branches:
              only: master
