export {default as borderProps, borderPropsDef} from './borderProps';
export {default as displayProps, displayPropsDef} from './displayProps';
export {default as flexProps, flexPropsDef} from './flexProps';
export {default as marginProps, marginPropsDef} from './marginProps';
export {default as paddingProps, paddingPropsDef} from './paddingProps';
export {default as positionProps, positionPropsDef} from './positionProps';
export {default as sizeProps, sizePropsDef} from './sizeProps';
export {default as textProps, textPropsDef} from './textProps';
export {default as themeProps, themePropsDef} from './themeProps';
